version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - shared_services
    volumes:
      - mongo_volume:/data/db
  redis:
    image: redis
    restart: always
    networks:
      - shared_services

networks:
  shared_services:
    external: true

volumes:
  mongo_volume:
