version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - shared_services
    volumes:
      - mongo_volume:/data/db
  redis:
    image: redis
    restart: always
    networks:
      - shared_services
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - shared_services
    volumes:
      - postgres_volume:/var/lib/postgresql/data

networks:
  shared_services:
    external: true

volumes:
  postgres_volume:
  mongo_volume:
